"""add progress fields to sync_runs

Revision ID: 2e57b0e4f645
Revises: c5a169e4d646
Create Date: 2026-09-12 17:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e57b0e4f645'
down_revision: Union[str, None] = 'c5a169e4d646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('progress_phase', sa.String(), nullable=True))
    op.add_column(
        'sync_runs',
        sa.Column('progress_current', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('sync_runs', sa.Column('progress_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'progress_total')
    op.drop_column('sync_runs', 'progress_current')
    op.drop_column('sync_runs', 'progress_phase')
    # ### end Alembic commands ###
