"""initial schema

Revision ID: 33ccb71a0783
Revises: 
Create Date: 2026-09-11 17:49:11.482444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ccb71a0783'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_key'), 'issues', ['key'], unique=True)
    op.create_index(op.f('ix_issues_project_key'), 'issues', ['project_key'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('worklogs_upserted', sa.Integer(), nullable=False),
    sa.Column('worklogs_deleted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('project_keys', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_sync_schedule_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_watermark', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_sync_state_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worklogs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('author_account_id', sa.String(), nullable=False),
    sa.Column('author_display_name', sa.String(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_utc_offset', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worklogs_author_account_id_work_date', 'worklogs', ['author_account_id', 'work_date'], unique=False)
    op.create_index('ix_worklogs_issue_id', 'worklogs', ['issue_id'], unique=False)
    op.create_index('ix_worklogs_work_date', 'worklogs', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worklogs_work_date', table_name='worklogs')
    op.drop_index('ix_worklogs_issue_id', table_name='worklogs')
    op.drop_index('ix_worklogs_author_account_id_work_date', table_name='worklogs')
    op.drop_table('worklogs')
    op.drop_table('sync_state')
    op.drop_table('sync_schedule')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_issues_project_key'), table_name='issues')
    op.drop_index(op.f('ix_issues_key'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
