"""add cancel_requested to sync_runs

Revision ID: a4b8114a40e5
Revises: 2e57b0e4f645
Create Date: 2026-09-14 13:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b8114a40e5'
down_revision: Union[str, None] = '2e57b0e4f645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sync_runs',
        sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'cancel_requested')
    # ### end Alembic commands ###
