"""add jql_filter to sync_schedule

Revision ID: c5a169e4d646
Revises: 33ccb71a0783
Create Date: 2026-09-12 17:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a169e4d646'
down_revision: Union[str, None] = '33ccb71a0783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_schedule', sa.Column('jql_filter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_schedule', 'jql_filter')
    # ### end Alembic commands ###
